service: parameter-store-replicator
configValidationMode: error

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs10.x
  versionFunctions: true
  memorySize: 128
  timeout: 120
  logRetentionInDays: 7
  stackName: parameter-store-replicator-${opt:stage, self:provider.stage}

  deploymentBucket:
    name: vela-devops-serverless

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameters"
        - "ssm:GetParameter"
        - "ssm:PutParameter"
        - "ssm:DeleteParameter"
        - "ssm:DeleteParameters"
      Resource: "*"

functions:
  replicate:
    package:
      include:
        - handler.js
        - node_modules
    environment:
      AWS_TARGET_REGION: ${opt:target_region}
    handler: handler.replicate
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.ssm"
            detail-type:
              - "Parameter Store Change"

